### ISSUE TITLE
[For discussion] Certificate Pinning as a potential threat mitigation.

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-alert-server#32]
"6) there does not appear to be any configuration to allow for certificate pinning.  If a user is connected to an untrusted mobile hotspot they may be coerced into communicating with a rogue Covid shield server."

As raised by external threat audit, lack of certificate pinning in the app was raised a potential concern.

I'm not entirely up-to-speed with the complexity this may add into the deployment/release process, but before going down this route, I'd like to have a well described threat model in place.

I don't see the initial example above as a valid attack vector, in that regardless of the 'sketchiness' of an untrusted hotspot, the browser will still only trust Certificates from a set of trusted Certificate Authorities, none of which is the mobile hot-spot.

<insert cert pinning threat model documentation here>

**Comment by SunChero** [comment]
i would say this is more of best practice nowadays.
doing this with react-native is complicated because RN doesnt these kind of ability by default.

in my opinion the risc here is valid .. its just really very low  compared to the complexity of doing/maintaining this especially in  react native.

This npm package, react-native-cert-pinner  should help if you decides going down this road 


btw, the browser settings and configurations does not apply here, its between a server and an http client (react-native )

let me know if i can help

good luck / bonne chance :)

**Comment by alyssarosenzweig** [comment]
For key retrieval, there's the `export.sig` file which is "supposed" to handle this (signed via the `ECDSA_KEY` parameter). Certificate pinning as a layer on top isn't a bad idea for defense-in-depth, but realistically even if the connection is attacked *and* a certificate authority is compromised, the mobile implementations will still fail the signature check.

Whether the signature check makes sense as added complexity in a world with HTTPS and certificate pinning is a different question, of course, but the exposure notifications framework doesn't give us that choice.

**Comment by maxneuvians** [comment]
Based on our observations, the opinions above and the following statement from AWS: `AWS doesn't recommend pinning your application to an SSL/TLS certificate issued by ACM` (https://aws.amazon.com/premiumsupport/knowledge-center/pin-application-acm-certificate/) I will close this for now. Can re-visit if guidance changes.
